package com.totoro.data.dao;

import com.totoro.data.model.LhbDetail;
import com.totoro.data.model.LhbDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LhbDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    long countByExample(LhbDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    int deleteByExample(LhbDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    int insert(LhbDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    int insertSelective(LhbDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    List<LhbDetail> selectByExample(LhbDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    LhbDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LhbDetail record, @Param("example") LhbDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LhbDetail record, @Param("example") LhbDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LhbDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LhbDetail record);

	void saveInfoList(List<LhbDetail> list);
}