package com.totoro.data.dao;

import com.totoro.core.model.UserInfo;
import com.totoro.data.model.LhbInfo;
import com.totoro.data.model.LhbInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LhbInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbinfo
     *
     * @mbg.generated
     */
    int countByExample(LhbInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbinfo
     *
     * @mbg.generated
     */
    int deleteByExample(LhbInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbinfo
     *
     * @mbg.generated
     */
    int insert(LhbInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbinfo
     *
     * @mbg.generated
     */
    int insertSelective(LhbInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbinfo
     *
     * @mbg.generated
     */
    List<LhbInfo> selectByExample(LhbInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbinfo
     *
     * @mbg.generated
     */
    LhbInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbinfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LhbInfo record, @Param("example") LhbInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbinfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LhbInfo record, @Param("example") LhbInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LhbInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LhbInfo record);

	int saveInfoList(List<LhbInfo> list);

	List<LhbInfo> selectDataPage(@Param("selectname")String selectname, @Param("page")Integer page, @Param("pagesize")Integer pagesize);
}