package com.totoro.data.dao;

import com.totoro.data.model.Node;
import com.totoro.data.model.Testaddr;
import com.totoro.data.model.TestaddrExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestaddrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testaddr
     *
     * @mbg.generated
     */
    long countByExample(TestaddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testaddr
     *
     * @mbg.generated
     */
    int deleteByExample(TestaddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testaddr
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testaddr
     *
     * @mbg.generated
     */
    int insert(Testaddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testaddr
     *
     * @mbg.generated
     */
    int insertSelective(Testaddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testaddr
     *
     * @mbg.generated
     */
    List<Testaddr> selectByExample(TestaddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testaddr
     *
     * @mbg.generated
     */
    Testaddr selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testaddr
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Testaddr record, @Param("example") TestaddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testaddr
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Testaddr record, @Param("example") TestaddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testaddr
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Testaddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testaddr
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Testaddr record);
    
    List<Node> selectAddr();
}