package com.totoro.data.model;

import java.math.BigDecimal;
import java.util.Date;

public class LhbDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_lhbdetail.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_lhbdetail.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_lhbdetail.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_lhbdetail.yyt
     *
     * @mbg.generated
     */
    private String yyt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_lhbdetail.buymoney
     *
     * @mbg.generated
     */
    private BigDecimal buymoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_lhbdetail.buyproportion
     *
     * @mbg.generated
     */
    private BigDecimal buyproportion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_lhbdetail.sellmoney
     *
     * @mbg.generated
     */
    private BigDecimal sellmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_lhbdetail.sellproportion
     *
     * @mbg.generated
     */
    private BigDecimal sellproportion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_lhbdetail.total
     *
     * @mbg.generated
     */
    private BigDecimal total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_lhbdetail.times
     *
     * @mbg.generated
     */
    private Integer times;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_lhbdetail.percent
     *
     * @mbg.generated
     */
    private String percent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_lhbdetail.percentcss
     *
     * @mbg.generated
     */
    private String percentcss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_lhbdetail.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_lhbdetail.id
     *
     * @return the value of data_lhbdetail.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_lhbdetail.id
     *
     * @param id the value for data_lhbdetail.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_lhbdetail.code
     *
     * @return the value of data_lhbdetail.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_lhbdetail.code
     *
     * @param code the value for data_lhbdetail.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_lhbdetail.type
     *
     * @return the value of data_lhbdetail.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_lhbdetail.type
     *
     * @param type the value for data_lhbdetail.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_lhbdetail.yyt
     *
     * @return the value of data_lhbdetail.yyt
     *
     * @mbg.generated
     */
    public String getYyt() {
        return yyt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_lhbdetail.yyt
     *
     * @param yyt the value for data_lhbdetail.yyt
     *
     * @mbg.generated
     */
    public void setYyt(String yyt) {
        this.yyt = yyt == null ? null : yyt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_lhbdetail.buymoney
     *
     * @return the value of data_lhbdetail.buymoney
     *
     * @mbg.generated
     */
    public BigDecimal getBuymoney() {
        return buymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_lhbdetail.buymoney
     *
     * @param buymoney the value for data_lhbdetail.buymoney
     *
     * @mbg.generated
     */
    public void setBuymoney(BigDecimal buymoney) {
        this.buymoney = buymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_lhbdetail.buyproportion
     *
     * @return the value of data_lhbdetail.buyproportion
     *
     * @mbg.generated
     */
    public BigDecimal getBuyproportion() {
        return buyproportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_lhbdetail.buyproportion
     *
     * @param buyproportion the value for data_lhbdetail.buyproportion
     *
     * @mbg.generated
     */
    public void setBuyproportion(BigDecimal buyproportion) {
        this.buyproportion = buyproportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_lhbdetail.sellmoney
     *
     * @return the value of data_lhbdetail.sellmoney
     *
     * @mbg.generated
     */
    public BigDecimal getSellmoney() {
        return sellmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_lhbdetail.sellmoney
     *
     * @param sellmoney the value for data_lhbdetail.sellmoney
     *
     * @mbg.generated
     */
    public void setSellmoney(BigDecimal sellmoney) {
        this.sellmoney = sellmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_lhbdetail.sellproportion
     *
     * @return the value of data_lhbdetail.sellproportion
     *
     * @mbg.generated
     */
    public BigDecimal getSellproportion() {
        return sellproportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_lhbdetail.sellproportion
     *
     * @param sellproportion the value for data_lhbdetail.sellproportion
     *
     * @mbg.generated
     */
    public void setSellproportion(BigDecimal sellproportion) {
        this.sellproportion = sellproportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_lhbdetail.total
     *
     * @return the value of data_lhbdetail.total
     *
     * @mbg.generated
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_lhbdetail.total
     *
     * @param total the value for data_lhbdetail.total
     *
     * @mbg.generated
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_lhbdetail.times
     *
     * @return the value of data_lhbdetail.times
     *
     * @mbg.generated
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_lhbdetail.times
     *
     * @param times the value for data_lhbdetail.times
     *
     * @mbg.generated
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_lhbdetail.percent
     *
     * @return the value of data_lhbdetail.percent
     *
     * @mbg.generated
     */
    public String getPercent() {
        return percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_lhbdetail.percent
     *
     * @param percent the value for data_lhbdetail.percent
     *
     * @mbg.generated
     */
    public void setPercent(String percent) {
        this.percent = percent == null ? null : percent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_lhbdetail.percentcss
     *
     * @return the value of data_lhbdetail.percentcss
     *
     * @mbg.generated
     */
    public String getPercentcss() {
        return percentcss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_lhbdetail.percentcss
     *
     * @param percentcss the value for data_lhbdetail.percentcss
     *
     * @mbg.generated
     */
    public void setPercentcss(String percentcss) {
        this.percentcss = percentcss == null ? null : percentcss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_lhbdetail.createtime
     *
     * @return the value of data_lhbdetail.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_lhbdetail.createtime
     *
     * @param createtime the value for data_lhbdetail.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}