package com.totoro.data.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class LhbDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    public LhbDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andYytIsNull() {
            addCriterion("yyt is null");
            return (Criteria) this;
        }

        public Criteria andYytIsNotNull() {
            addCriterion("yyt is not null");
            return (Criteria) this;
        }

        public Criteria andYytEqualTo(String value) {
            addCriterion("yyt =", value, "yyt");
            return (Criteria) this;
        }

        public Criteria andYytNotEqualTo(String value) {
            addCriterion("yyt <>", value, "yyt");
            return (Criteria) this;
        }

        public Criteria andYytGreaterThan(String value) {
            addCriterion("yyt >", value, "yyt");
            return (Criteria) this;
        }

        public Criteria andYytGreaterThanOrEqualTo(String value) {
            addCriterion("yyt >=", value, "yyt");
            return (Criteria) this;
        }

        public Criteria andYytLessThan(String value) {
            addCriterion("yyt <", value, "yyt");
            return (Criteria) this;
        }

        public Criteria andYytLessThanOrEqualTo(String value) {
            addCriterion("yyt <=", value, "yyt");
            return (Criteria) this;
        }

        public Criteria andYytLike(String value) {
            addCriterion("yyt like", value, "yyt");
            return (Criteria) this;
        }

        public Criteria andYytNotLike(String value) {
            addCriterion("yyt not like", value, "yyt");
            return (Criteria) this;
        }

        public Criteria andYytIn(List<String> values) {
            addCriterion("yyt in", values, "yyt");
            return (Criteria) this;
        }

        public Criteria andYytNotIn(List<String> values) {
            addCriterion("yyt not in", values, "yyt");
            return (Criteria) this;
        }

        public Criteria andYytBetween(String value1, String value2) {
            addCriterion("yyt between", value1, value2, "yyt");
            return (Criteria) this;
        }

        public Criteria andYytNotBetween(String value1, String value2) {
            addCriterion("yyt not between", value1, value2, "yyt");
            return (Criteria) this;
        }

        public Criteria andBuymoneyIsNull() {
            addCriterion("buymoney is null");
            return (Criteria) this;
        }

        public Criteria andBuymoneyIsNotNull() {
            addCriterion("buymoney is not null");
            return (Criteria) this;
        }

        public Criteria andBuymoneyEqualTo(BigDecimal value) {
            addCriterion("buymoney =", value, "buymoney");
            return (Criteria) this;
        }

        public Criteria andBuymoneyNotEqualTo(BigDecimal value) {
            addCriterion("buymoney <>", value, "buymoney");
            return (Criteria) this;
        }

        public Criteria andBuymoneyGreaterThan(BigDecimal value) {
            addCriterion("buymoney >", value, "buymoney");
            return (Criteria) this;
        }

        public Criteria andBuymoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("buymoney >=", value, "buymoney");
            return (Criteria) this;
        }

        public Criteria andBuymoneyLessThan(BigDecimal value) {
            addCriterion("buymoney <", value, "buymoney");
            return (Criteria) this;
        }

        public Criteria andBuymoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("buymoney <=", value, "buymoney");
            return (Criteria) this;
        }

        public Criteria andBuymoneyIn(List<BigDecimal> values) {
            addCriterion("buymoney in", values, "buymoney");
            return (Criteria) this;
        }

        public Criteria andBuymoneyNotIn(List<BigDecimal> values) {
            addCriterion("buymoney not in", values, "buymoney");
            return (Criteria) this;
        }

        public Criteria andBuymoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("buymoney between", value1, value2, "buymoney");
            return (Criteria) this;
        }

        public Criteria andBuymoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("buymoney not between", value1, value2, "buymoney");
            return (Criteria) this;
        }

        public Criteria andBuyproportionIsNull() {
            addCriterion("buyproportion is null");
            return (Criteria) this;
        }

        public Criteria andBuyproportionIsNotNull() {
            addCriterion("buyproportion is not null");
            return (Criteria) this;
        }

        public Criteria andBuyproportionEqualTo(BigDecimal value) {
            addCriterion("buyproportion =", value, "buyproportion");
            return (Criteria) this;
        }

        public Criteria andBuyproportionNotEqualTo(BigDecimal value) {
            addCriterion("buyproportion <>", value, "buyproportion");
            return (Criteria) this;
        }

        public Criteria andBuyproportionGreaterThan(BigDecimal value) {
            addCriterion("buyproportion >", value, "buyproportion");
            return (Criteria) this;
        }

        public Criteria andBuyproportionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("buyproportion >=", value, "buyproportion");
            return (Criteria) this;
        }

        public Criteria andBuyproportionLessThan(BigDecimal value) {
            addCriterion("buyproportion <", value, "buyproportion");
            return (Criteria) this;
        }

        public Criteria andBuyproportionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("buyproportion <=", value, "buyproportion");
            return (Criteria) this;
        }

        public Criteria andBuyproportionIn(List<BigDecimal> values) {
            addCriterion("buyproportion in", values, "buyproportion");
            return (Criteria) this;
        }

        public Criteria andBuyproportionNotIn(List<BigDecimal> values) {
            addCriterion("buyproportion not in", values, "buyproportion");
            return (Criteria) this;
        }

        public Criteria andBuyproportionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("buyproportion between", value1, value2, "buyproportion");
            return (Criteria) this;
        }

        public Criteria andBuyproportionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("buyproportion not between", value1, value2, "buyproportion");
            return (Criteria) this;
        }

        public Criteria andSellmoneyIsNull() {
            addCriterion("sellmoney is null");
            return (Criteria) this;
        }

        public Criteria andSellmoneyIsNotNull() {
            addCriterion("sellmoney is not null");
            return (Criteria) this;
        }

        public Criteria andSellmoneyEqualTo(BigDecimal value) {
            addCriterion("sellmoney =", value, "sellmoney");
            return (Criteria) this;
        }

        public Criteria andSellmoneyNotEqualTo(BigDecimal value) {
            addCriterion("sellmoney <>", value, "sellmoney");
            return (Criteria) this;
        }

        public Criteria andSellmoneyGreaterThan(BigDecimal value) {
            addCriterion("sellmoney >", value, "sellmoney");
            return (Criteria) this;
        }

        public Criteria andSellmoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sellmoney >=", value, "sellmoney");
            return (Criteria) this;
        }

        public Criteria andSellmoneyLessThan(BigDecimal value) {
            addCriterion("sellmoney <", value, "sellmoney");
            return (Criteria) this;
        }

        public Criteria andSellmoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sellmoney <=", value, "sellmoney");
            return (Criteria) this;
        }

        public Criteria andSellmoneyIn(List<BigDecimal> values) {
            addCriterion("sellmoney in", values, "sellmoney");
            return (Criteria) this;
        }

        public Criteria andSellmoneyNotIn(List<BigDecimal> values) {
            addCriterion("sellmoney not in", values, "sellmoney");
            return (Criteria) this;
        }

        public Criteria andSellmoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sellmoney between", value1, value2, "sellmoney");
            return (Criteria) this;
        }

        public Criteria andSellmoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sellmoney not between", value1, value2, "sellmoney");
            return (Criteria) this;
        }

        public Criteria andSellproportionIsNull() {
            addCriterion("sellproportion is null");
            return (Criteria) this;
        }

        public Criteria andSellproportionIsNotNull() {
            addCriterion("sellproportion is not null");
            return (Criteria) this;
        }

        public Criteria andSellproportionEqualTo(BigDecimal value) {
            addCriterion("sellproportion =", value, "sellproportion");
            return (Criteria) this;
        }

        public Criteria andSellproportionNotEqualTo(BigDecimal value) {
            addCriterion("sellproportion <>", value, "sellproportion");
            return (Criteria) this;
        }

        public Criteria andSellproportionGreaterThan(BigDecimal value) {
            addCriterion("sellproportion >", value, "sellproportion");
            return (Criteria) this;
        }

        public Criteria andSellproportionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sellproportion >=", value, "sellproportion");
            return (Criteria) this;
        }

        public Criteria andSellproportionLessThan(BigDecimal value) {
            addCriterion("sellproportion <", value, "sellproportion");
            return (Criteria) this;
        }

        public Criteria andSellproportionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sellproportion <=", value, "sellproportion");
            return (Criteria) this;
        }

        public Criteria andSellproportionIn(List<BigDecimal> values) {
            addCriterion("sellproportion in", values, "sellproportion");
            return (Criteria) this;
        }

        public Criteria andSellproportionNotIn(List<BigDecimal> values) {
            addCriterion("sellproportion not in", values, "sellproportion");
            return (Criteria) this;
        }

        public Criteria andSellproportionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sellproportion between", value1, value2, "sellproportion");
            return (Criteria) this;
        }

        public Criteria andSellproportionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sellproportion not between", value1, value2, "sellproportion");
            return (Criteria) this;
        }

        public Criteria andTotalIsNull() {
            addCriterion("total is null");
            return (Criteria) this;
        }

        public Criteria andTotalIsNotNull() {
            addCriterion("total is not null");
            return (Criteria) this;
        }

        public Criteria andTotalEqualTo(BigDecimal value) {
            addCriterion("total =", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotEqualTo(BigDecimal value) {
            addCriterion("total <>", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalGreaterThan(BigDecimal value) {
            addCriterion("total >", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("total >=", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalLessThan(BigDecimal value) {
            addCriterion("total <", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("total <=", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalIn(List<BigDecimal> values) {
            addCriterion("total in", values, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotIn(List<BigDecimal> values) {
            addCriterion("total not in", values, "total");
            return (Criteria) this;
        }

        public Criteria andTotalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total between", value1, value2, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total not between", value1, value2, "total");
            return (Criteria) this;
        }

        public Criteria andTimesIsNull() {
            addCriterion("times is null");
            return (Criteria) this;
        }

        public Criteria andTimesIsNotNull() {
            addCriterion("times is not null");
            return (Criteria) this;
        }

        public Criteria andTimesEqualTo(Integer value) {
            addCriterion("times =", value, "times");
            return (Criteria) this;
        }

        public Criteria andTimesNotEqualTo(Integer value) {
            addCriterion("times <>", value, "times");
            return (Criteria) this;
        }

        public Criteria andTimesGreaterThan(Integer value) {
            addCriterion("times >", value, "times");
            return (Criteria) this;
        }

        public Criteria andTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("times >=", value, "times");
            return (Criteria) this;
        }

        public Criteria andTimesLessThan(Integer value) {
            addCriterion("times <", value, "times");
            return (Criteria) this;
        }

        public Criteria andTimesLessThanOrEqualTo(Integer value) {
            addCriterion("times <=", value, "times");
            return (Criteria) this;
        }

        public Criteria andTimesIn(List<Integer> values) {
            addCriterion("times in", values, "times");
            return (Criteria) this;
        }

        public Criteria andTimesNotIn(List<Integer> values) {
            addCriterion("times not in", values, "times");
            return (Criteria) this;
        }

        public Criteria andTimesBetween(Integer value1, Integer value2) {
            addCriterion("times between", value1, value2, "times");
            return (Criteria) this;
        }

        public Criteria andTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("times not between", value1, value2, "times");
            return (Criteria) this;
        }

        public Criteria andPercentIsNull() {
            addCriterion("percent is null");
            return (Criteria) this;
        }

        public Criteria andPercentIsNotNull() {
            addCriterion("percent is not null");
            return (Criteria) this;
        }

        public Criteria andPercentEqualTo(String value) {
            addCriterion("percent =", value, "percent");
            return (Criteria) this;
        }

        public Criteria andPercentNotEqualTo(String value) {
            addCriterion("percent <>", value, "percent");
            return (Criteria) this;
        }

        public Criteria andPercentGreaterThan(String value) {
            addCriterion("percent >", value, "percent");
            return (Criteria) this;
        }

        public Criteria andPercentGreaterThanOrEqualTo(String value) {
            addCriterion("percent >=", value, "percent");
            return (Criteria) this;
        }

        public Criteria andPercentLessThan(String value) {
            addCriterion("percent <", value, "percent");
            return (Criteria) this;
        }

        public Criteria andPercentLessThanOrEqualTo(String value) {
            addCriterion("percent <=", value, "percent");
            return (Criteria) this;
        }

        public Criteria andPercentLike(String value) {
            addCriterion("percent like", value, "percent");
            return (Criteria) this;
        }

        public Criteria andPercentNotLike(String value) {
            addCriterion("percent not like", value, "percent");
            return (Criteria) this;
        }

        public Criteria andPercentIn(List<String> values) {
            addCriterion("percent in", values, "percent");
            return (Criteria) this;
        }

        public Criteria andPercentNotIn(List<String> values) {
            addCriterion("percent not in", values, "percent");
            return (Criteria) this;
        }

        public Criteria andPercentBetween(String value1, String value2) {
            addCriterion("percent between", value1, value2, "percent");
            return (Criteria) this;
        }

        public Criteria andPercentNotBetween(String value1, String value2) {
            addCriterion("percent not between", value1, value2, "percent");
            return (Criteria) this;
        }

        public Criteria andPercentcssIsNull() {
            addCriterion("percentcss is null");
            return (Criteria) this;
        }

        public Criteria andPercentcssIsNotNull() {
            addCriterion("percentcss is not null");
            return (Criteria) this;
        }

        public Criteria andPercentcssEqualTo(String value) {
            addCriterion("percentcss =", value, "percentcss");
            return (Criteria) this;
        }

        public Criteria andPercentcssNotEqualTo(String value) {
            addCriterion("percentcss <>", value, "percentcss");
            return (Criteria) this;
        }

        public Criteria andPercentcssGreaterThan(String value) {
            addCriterion("percentcss >", value, "percentcss");
            return (Criteria) this;
        }

        public Criteria andPercentcssGreaterThanOrEqualTo(String value) {
            addCriterion("percentcss >=", value, "percentcss");
            return (Criteria) this;
        }

        public Criteria andPercentcssLessThan(String value) {
            addCriterion("percentcss <", value, "percentcss");
            return (Criteria) this;
        }

        public Criteria andPercentcssLessThanOrEqualTo(String value) {
            addCriterion("percentcss <=", value, "percentcss");
            return (Criteria) this;
        }

        public Criteria andPercentcssLike(String value) {
            addCriterion("percentcss like", value, "percentcss");
            return (Criteria) this;
        }

        public Criteria andPercentcssNotLike(String value) {
            addCriterion("percentcss not like", value, "percentcss");
            return (Criteria) this;
        }

        public Criteria andPercentcssIn(List<String> values) {
            addCriterion("percentcss in", values, "percentcss");
            return (Criteria) this;
        }

        public Criteria andPercentcssNotIn(List<String> values) {
            addCriterion("percentcss not in", values, "percentcss");
            return (Criteria) this;
        }

        public Criteria andPercentcssBetween(String value1, String value2) {
            addCriterion("percentcss between", value1, value2, "percentcss");
            return (Criteria) this;
        }

        public Criteria andPercentcssNotBetween(String value1, String value2) {
            addCriterion("percentcss not between", value1, value2, "percentcss");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterionForJDBCDate("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterionForJDBCDate("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterionForJDBCDate("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterionForJDBCDate("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_lhbdetail
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table data_lhbdetail
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}