package com.totoro.data.model;

import java.math.BigDecimal;
import java.util.Date;

public class LhbInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_lhbinfo.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_lhbinfo.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_lhbinfo.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_lhbinfo.range
     *
     * @mbg.generated
     */
    private BigDecimal ranges;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_lhbinfo.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_lhbinfo.id
     *
     * @return the value of data_lhbinfo.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_lhbinfo.id
     *
     * @param id the value for data_lhbinfo.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_lhbinfo.name
     *
     * @return the value of data_lhbinfo.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_lhbinfo.name
     *
     * @param name the value for data_lhbinfo.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_lhbinfo.code
     *
     * @return the value of data_lhbinfo.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_lhbinfo.code
     *
     * @param code the value for data_lhbinfo.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_lhbinfo.range
     *
     * @return the value of data_lhbinfo.range
     *
     * @mbg.generated
     */
    public BigDecimal getRanges() {
        return ranges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_lhbinfo.range
     *
     * @param range the value for data_lhbinfo.range
     *
     * @mbg.generated
     */
    public void setRanges(BigDecimal ranges) {
        this.ranges = ranges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_lhbinfo.createtime
     *
     * @return the value of data_lhbinfo.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_lhbinfo.createtime
     *
     * @param createtime the value for data_lhbinfo.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}