package com.zpj.sys.entity;
// Generated 2018-2-27 10:00:58 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysUploadFile generated by hbm2java
 */
@Entity
@Table(name = "SYS_UploadFile")
public class SysUploadFile implements java.io.Serializable {

	private String fileId;
	private Date createDate;
	private String fileName;
	private String fileAlias;
	private String fileUrl;
	private String fileType;
	private int fileSize;
	private String fileRemark;
	private String tableid;
	private String modeltype;

	public SysUploadFile() {
	}

	public SysUploadFile(String fileId, Date createDate, String fileName, String fileAlias,
			String fileUrl, String fileType, int fileSize) {
		this.fileId = fileId;
		this.createDate = createDate;
		this.fileName = fileName;
		this.fileAlias = fileAlias;
		this.fileUrl = fileUrl;
		this.fileType = fileType;
		this.fileSize = fileSize;
	}

	public SysUploadFile(String fileId, Date createDate, String fileName, String fileAlias,
			String fileUrl, String fileType, int fileSize, String fileRemark) {
		this.fileId = fileId;
		this.createDate = createDate;
		this.fileName = fileName;
		this.fileAlias = fileAlias;
		this.fileUrl = fileUrl;
		this.fileType = fileType;
		this.fileSize = fileSize;
		this.fileRemark = fileRemark;
	}

	@Id
	@Column(name = "FileID", unique = true, nullable = false,length=50)
	public String getFileId() {
		return this.fileId;
	}

	public void setFileId(String fileId) {
		this.fileId = fileId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", nullable = false, length = 23)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "FileName", nullable = false)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "FileAlias", nullable = false)
	public String getFileAlias() {
		return this.fileAlias;
	}

	public void setFileAlias(String fileAlias) {
		this.fileAlias = fileAlias;
	}

	@Column(name = "FileUrl", nullable = false)
	public String getFileUrl() {
		return this.fileUrl;
	}

	public void setFileUrl(String fileUrl) {
		this.fileUrl = fileUrl;
	}

	@Column(name = "FileType", nullable = false)
	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	@Column(name = "FileSize", nullable = false)
	public int getFileSize() {
		return this.fileSize;
	}

	public void setFileSize(int fileSize) {
		this.fileSize = fileSize;
	}

	@Column(name = "FileRemark")
	public String getFileRemark() {
		return this.fileRemark;
	}

	public void setFileRemark(String fileRemark) {
		this.fileRemark = fileRemark;
	}

	public String getTableid() {
		return tableid;
	}
	public void setTableid(String tableid) {
		this.tableid = tableid;
	}

	public String getModeltype() {
		return modeltype;
	}
	public void setModeltype(String modeltype) {
		this.modeltype = modeltype;
	}
}
