package com.zpj.sys.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import io.swagger.annotations.ApiModel;


/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "sys_userinfo")
@ApiModel(value = "用户表", description = "用户信息表")
public class User implements java.io.Serializable {
	private String id;//id
	private String name;//名称
	
	
	@Id
	@Column()
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}

	

}
