package com.zpj.sys.entity;


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "sys_userinfo")
@ApiModel(value = "用户表", description = "用户信息表")
public class User implements java.io.Serializable {
	
	@ApiModelProperty(value = "主键",name="id", required = true)
	private String id;//id
	@ApiModelProperty(value = "姓名",name="name", required =  false)
	private String name;//名称
	@ApiModelProperty(value = "登陆名称",name="loginName", required =  false)
	private String loginName;
	@ApiModelProperty(value = "密码",name="password", required =  false)
	private String password;//密码
	@ApiModelProperty(value = "邮箱",name="email", required =  false)
	private String email;
	@ApiModelProperty(value = "性别，0男，1女，2保密",name="sex", required =  false)
	private String sex;//0男，女1,保密2
	@ApiModelProperty(value = "会员等级，0普通，1注册，2中级，3高级",name="priority", required =  false)
	private String priority;//优先级
	@ApiModelProperty(value = "状态，0正常，1禁用",name="state", required =  false)
	private String state;
	@ApiModelProperty(value = "时间",name="createTime", required =  false)
	private Date createTime;
	private Date lastLoginTime;
	@ApiModelProperty(value = "描述",name="descirption", required =  false)
	private String description;//描述
	
	private String isAdmin;//1是，0不是

	public User(){

	}
	public User(String id,String name,String password){
		this.id=id;
		this.name=name;
		this.password=password;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false ,length=36)
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	public String getLoginName() {
		return loginName;
	}
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getSex() {
		return sex;
	}
	public void setSex(String sex) {
		this.sex = sex;
	}
	
	public String getPriority() {
		return priority;
	}
	public void setPriority(String priority) {
		this.priority = priority;
	}
	public String getState() {
		return state;
	}
	public void setState(String state) {
		this.state = state;
	}
	@Temporal(value=TemporalType.TIMESTAMP)
	public Date getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	public Date getLastLoginTime() {
		return lastLoginTime;
	}
	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}

	@Transient
	public String getIsAdmin() {
		return isAdmin;
	}

	public void setIsAdmin(String isAdmin) {
		this.isAdmin = isAdmin;
	}
	

}
